:Author: shaileshverma21
:Email:
:Date: 16/08/2025
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===

Pin Number = D3 is connected to ESP 32 D13 status of the drive B 
=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
/*
#include <DHT.h>

#include <DHT_U.h>

 

//#include <MUIU8g2.h>

#include <U8g2lib.h>

#include <U8x8lib.h>

#include <arduino-timer.h>

#include <WiFiNINA.h>

#include <utility/wifi_drv.h>

//MKR WiFi 1010 to TMS320F28379D communication

//#define TX_PIN 14

//#define RX_PIN 13

/*

  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"

  https://create.arduino.cc/cloud/things/e0e3595f-2602-4288-9a6b-99afd8c354ab

 

  Arduino IoT Cloud Variables description

 

  The following variables are automatically generated and updated when changes are made to the Thing

 

  String message_one;

  CloudLight button;

  CloudLight drive_OFF;

  CloudLight drive_ON;

  CloudLight Drive_Run;

  CloudLight Drive_Stop;

  CloudLight led_on_off;

  CloudTemperatureSensor temperature;

  int led_pwd;

  int pot;

  CloudRelativeHumidity humidity;

  CloudSchedule timer;

 

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions

  which are called when their values are changed from the Dashboard.

  These functions are generated with the Thing and added at the end of this sketch.

*/

 

#include "thingProperties.h"

#define DHTPIN A1

#define DHTTYPE DHT11

 

DHT dht(DHTPIN, DHTTYPE);

 

auto sensor_timer = timer_create_default(); // create a timer with default settings

U8G2_SH1106_128X64_NONAME_F_HW_I2C u8g2(U8G2_R0, /* reset=*/ U8X8_PIN_NONE);

 

bool get_button_pot_state(void *) {

  pot = analogRead(A6);

  button = digitalRead(0);

  printValues();

  return true; // repeat? true

}

 

 

 

void setup() {

  // Initialize serial and wait for port to open:

  Serial.begin(9600);

// Serial1.begin(115200, SERIAL_8N1, RX_PIN, TX_PIN);

 

  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found

  analogReadResolution(12);

  delay(1500);

 pinMode(6,OUTPUT);

pinMode(A6,INPUT);

  pinMode(A1,INPUT);

  pinMode(5,OUTPUT);

  pinMode(0,INPUT_PULLUP);

    dht.begin();

  WiFiDrv::pinMode(25, OUTPUT); //define green pin

  WiFiDrv::pinMode(26, OUTPUT); //define red pin

  WiFiDrv::pinMode(27, OUTPUT); //define blue pin

 

 

 

 

  // Defined in thingProperties.h

  initProperties();

 

  // Connect to Arduino IoT Cloud

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

 

  u8g2.begin();

 

  u8g2.clearBuffer();

  u8g2.setFont(u8g2_font_helvB18_tf);

  u8g2.drawStr(0, 30,"Starting...");

  u8g2.sendBuffer();

 

  /*

     The following function allows you to obtain more information

     related to the state of network and IoT Cloud connection and errors

     the higher number the more granular information you’ll get.

     The default is 0 (only errors).

     Maximum is 4

*/

  setDebugMessageLevel(2);

  ArduinoCloud.printDebugInfo();

 

   sensor_timer.every(500, get_button_pot_state);

// sensor_timer.every(5000, get_sensor_readings);

 

 

}

 

void loop() {

  ArduinoCloud.update();

  // Your code here

  DHT_SENSOR_READ();

   sensor_timer.tick(); // tick the timer

  if (timer.isActive()){

    WiFiDrv::analogWrite(25, 255); // turn on Green LED in RGB

    WiFiDrv::analogWrite(26, 0); // turn off Red LED in RGB

    WiFiDrv::analogWrite(27, 0); // turn off Blue LED in RGB

  } else

  {

    WiFiDrv::analogWrite(25, 0); // turn off Green LED in RGB

    WiFiDrv::analogWrite(26, 0); // turn off Red LED in RGB

    WiFiDrv::analogWrite(27, 255); // turn on Blue LED in RGB

  }

 

/* Sending data packet every500 ms* added 21082025

static unsigned long lastSend = 0;

  if (millis() - lastSend > 500) {

    sendDataToF28379D();

    lastSend = millis();

  }*/

}

/*

  Since LedOnOff is READ_WRITE variable, onLedOnOffChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onLedOnOffChange()  {

  // Add your code here to act upon LedOnOff change

 

  // if(led_on_off)

  // {

  //   digitalWrite(6,HIGH);

  //   Serial.println("Button ON");

  // }

  // else

  // {

  // digitalWrite(6,LOW);

  //  Serial.println("Button OFF");

 

   

  // }

}

 

 

/*

  Since DriveON is READ_WRITE variable, onDriveONChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onDriveONChange()  {

  // Add your code here to act upon DriveON change

if(drive_ON)

{

  digitalWrite(6,HIGH);

    Serial.println("Drive ON");

   Drive_Stop=0;

   Drive_Run=1;

     

}

}

 

/*

  Since DriveOFF is READ_WRITE variable, onDriveOFFChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onDriveOFFChange()  {

  // Add your code here to act upon DriveOFF change

if(drive_OFF)

{

 

 digitalWrite(6,LOW);

   Serial.println("Drive OFF");

   Drive_Stop=1;

   Drive_Run=0;

}

}

 

 

 

/*

  Since DriveRun is READ_WRITE variable, onDriveRunChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onDriveRunChange()  {

  // Add your code here to act upon DriveRun change

}

 

/*

  Since DriveStop is READ_WRITE variable, onDriveStopChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onDriveStopChange()  {

  // Add your code here to act upon DriveStop change

}

 

 

void printValues() {

    Serial.print("Button: ");

    Serial.println(button);

    Serial.print("pot: ");

    Serial.println(pot);

    Serial.print("led_pwd: ");

    Serial.println(led_pwd);

    Serial.println(temperature);

    Serial.println(humidity);

    Serial.println();

   update_oled();

}

 

/*

  Since Button is READ_WRITE variable, onButtonChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onButtonChange()  {

  // Add your code here to act upon Button change

}

 

/*

  Since LedPwd is READ_WRITE variable, onLedPwdChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onLedPwdChange()  {

  // Add your code here to act upon LedPwd change

 

  // Add your code here to act upon LedPwd change

  analogWrite(5,led_pwd);

  Serial.println(led_pwd);

 

}

 

/*

  Since Pot is READ_WRITE variable, onPotChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onPotChange()  {

  // Add your code here to act upon Pot change

}

 

void update_oled()

{

  u8g2.clearBuffer();

  u8g2.setFont(u8g2_font_luRS10_tf);

  u8g2.setFontPosTop();

 

  u8g2.setCursor(1, 5);

u8g2.print(String(temperature) + (char)176 + "C");

  //u8g2.print("String(temperature)" + (char)176 + "C");

  //u8g2.print("24 C");

  u8g2.setCursor(85, 25);

 

  u8g2.print(String(humidity,1) + "%");  // Round humidity float to 1 decimal so it fits.

  // u8g2.print(String(humidity,1) + "%");  // Round humidity float to 1 decimal so it fits.

//u8g2.print("64.3%");  // Round humidity float to 1 decimal so it fits.

  u8g2.setCursor(1, 45);

  u8g2.print(pot);

 

  u8g2.setCursor(1, 25);

//  u8g2.print(String(pressure) + "hPa");

  u8g2.print("23 hPa");

  u8g2.setCursor(105, 5);

    if (button)

      u8g2.print("Off");

    else

      u8g2.print("On");

 

  u8g2.setCursor(40, 45);

  u8g2.print(message_one);

 

  u8g2.sendBuffer();

}

 

/*

  Since Timer is READ_WRITE variable, onTimerChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onTimerChange()  {

  // Add your code here to act upon Timer change

}

 

/*

  Since MessageOne is READ_WRITE variable, onMessageOneChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onMessageOneChange()  {

  // Add your code here to act upon MessageOne change

  update_oled();

}

 

void DHT_SENSOR_READ()

 


{

 

float h = dht.readHumidity();

 


 

  float t=dht.readTemperature();

 


 

  temperature = t;

 

  humidity= h;

 

 

 

 

  Serial.print("Temperture - ");Serial.println(t);

 

  Serial.print("Humidity - ");Serial.println(h);

 

 

  

    printValues();

 

delay(1000);

 


 


 


 


 

}

 

/*

  Since Temperature is READ_WRITE variable, onTemperatureChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onTemperatureChange()  {

  // Add your code here to act upon Temperature change

}

 

/*

  Since Humidity is READ_WRITE variable, onHumidityChange() is

  executed every time a new value is received from IoT Cloud.

*/

void onHumidityChange()  {

  // Add your code here to act upon Humidity change

}


read and transmit 
  if(s=='a')
    {
      Serial1.write('a');      
      
    }
    if(s=='b')
    {
      Serial1.write('b');      
      
    }
  }

  if(Serial1.available()>0)
  {
    int t=Serial1.read();
    if(t=='a')
    {
      digitalWrite(5,HIGH);
    }
    if(t=='b')
    {
      digitalWrite(5,LOW);
    }
  }
  
    
}
--------------------------------
void receiveDataFromF28379D() {
  if (Serial1.available()) {
    String received_data = Serial1.readStringUntil('E');
    
    // Check if data starts with 'S'
    if (received_data.charAt(0) == 'S') {
      // Remove the start marker
      received_data = received_data.substring(1);
      
      // Parse the binary values
      int recv_button = received_data.charAt(0) - '0';
      int recv_drive_OFF = received_data.charAt(1) - '0';
      int recv_drive_ON = received_data.charAt(2) - '0';
      int recv_Drive_Run = received_data.charAt(3) - '0';
      int recv_Drive_Stop = received_data.charAt(4) - '0';
      int recv_led_on_off = received_data.charAt(5) - '0';
      
      // Find positions for numerical data
      int pos = 6;
      int endPos = received_data.indexOf('E', pos);
      if (endPos == -1) endPos = received_data.length();
      
      // Parse temperature, led_pwd, pot, humidity
      String temp_str = received_data.substring(pos, pos + 4);
      int recv_temp = temp_str.toInt();
      
      pos += temp_str.length();
      String led_pwd_str = received_data.substring(pos, pos + 3);
      int recv_led_pwd = led_pwd_str.toInt();
      
      pos += led_pwd_str.length();
      String pot_str = received_data.substring(pos, pos + 4);
      int recv_pot = pot_str.toInt();
      
      pos += pot_str.length();
      String humidity_str = received_data.substring(pos);
      int recv_humidity = humidity_str.toInt();
      
      // Process the received data as needed
      Serial.println("Received data from F28379D:");
      Serial.println("Button: " + String(recv_button));
      Serial.println("Temp: " + String(recv_temp/100.0));
      Serial.println("LED PWD: " + String(recv_led_pwd));
    }
  }
}
*/
