// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessageOneChange();
void onButtonChange();
void onDriveCHBOFFChange();
void onDriveCHBONChange();
void onDriveRunChange();
void onDriveStopChange();
void onLedOnOffChange();
void onRelay1Change();
void onTemperatureChange();
void onLedPwdChange();
void onPotChange();
void onServo1Change();
void onHumidityChange();
void onTimerChange();

String message_one;
CloudLight button;
CloudLight drive_CHB_OFF;
CloudLight drive_CHB_ON;
CloudLight Drive_Run;
CloudLight Drive_Stop;
CloudLight led_on_off;
CloudLight relay_1;
CloudTemperatureSensor temperature;
int led_pwd;
int pot;
int servo_1;
CloudRelativeHumidity humidity;
CloudSchedule timer;

void initProperties(){

  ArduinoCloud.addProperty(message_one, READWRITE, ON_CHANGE, onMessageOneChange);
  ArduinoCloud.addProperty(button, READWRITE, ON_CHANGE, onButtonChange);
  ArduinoCloud.addProperty(drive_CHB_OFF, READWRITE, ON_CHANGE, onDriveCHBOFFChange);
  ArduinoCloud.addProperty(drive_CHB_ON, READWRITE, ON_CHANGE, onDriveCHBONChange);
  ArduinoCloud.addProperty(Drive_Run, READWRITE, ON_CHANGE, onDriveRunChange);
  ArduinoCloud.addProperty(Drive_Stop, READWRITE, ON_CHANGE, onDriveStopChange);
  ArduinoCloud.addProperty(led_on_off, READWRITE, ON_CHANGE, onLedOnOffChange);
  ArduinoCloud.addProperty(relay_1, READWRITE, ON_CHANGE, onRelay1Change);
  ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(led_pwd, READWRITE, ON_CHANGE, onLedPwdChange);
  ArduinoCloud.addProperty(pot, READWRITE, ON_CHANGE, onPotChange);
  ArduinoCloud.addProperty(servo_1, READWRITE, ON_CHANGE, onServo1Change);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);
  ArduinoCloud.addProperty(timer, READWRITE, ON_CHANGE, onTimerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
